### ISSUE TITLE
squareBracket Roadmap

### ISSUE THREAD

**Issue by PF94** [chazizgrkb/squarebracket#33]
# Alpha 3

- [x]  Resolve bad design decisions taken in Alpha 1 and 2 (Milestone)
- [x]  Proper profiles
- [x]  Improve translations
- [x]  Migrate PokTube accounts
## Alpha 3 Refresh
- [x]  Add option to change profile picture (and banner)
- [x]  Proper video uploader.
- [x] Proper password resetting
# Pre-Beta
- [x]  Add the ability for the user to reset their token. essentially logging all of their devices out from the account.
# Beta-era
## Beta 1.x
- [x]  Ability to lock the website in the case of a raid happening. (Maintenance mode)
## Beta 2.0.x
- [ ]  Admin Dashboard
- [x] #73
- [ ] Move from H264 to VP9 (fixes #76)
- [ ] Finish sbNext (closes #40)
- [ ] Relaunch production server (fixes #71)
- [x] Actually finish the goddamn forums
- [x] #86
- [x] redesign most of the css to follow a style (hitchhiker? Cosmic panda?)
- [ ] squareBracket studio
- [x] make the sounds not loud
- [ ] improve the music page
- [ ] add a browse music page
- [x] fix the navbar not looking good on mobile
- [x] make register.php no longer use bootstrap
- [ ] finobe-esque about/tos/privacy policy pages
- [x] block curl bots by logging IP addresses
- [x] delete bootstrap from existence
- [ ] replace old sb permissions system with new principia-web permissions system
- [x] #141
- [x] alternative frontend, poktube ui perhaps?
- [ ] clean up/refactor codebase
- [ ] #93
- [x] have our project ranted by the folks at subrocks for the 9999th time in a row
- [x] subrocks shuts down due to extreme drama in their community lmao
- [x] #92
- [ ] fix ass audio compression on videos
- [x] #91
- [x] use mp4 for when a browser doesn’t support mpeg-dash (example: vanilla basic chromium, and apprantly safari?), this would be better than vp9 as that shit would require the entire player to be rewritten
- [ ] add a countdown system for unreleased videos like several robloxians season 2 episode 0 (not like youtube premieres as premieres are more like livestreams)
- [x] #90
- [ ] more discord webhooks for better intergration with gamerappium/hyperborea
- [x] #89

**Comment by chaziz94** [comment]
updated roadmap

**Comment by chaziz94** [comment]
updated roadmap again

**Comment by cr-contributors** [comment]
> updated roadmap again

ok

**Comment by PF94** [comment]
really redudant
